debug: ${debug}
enable playground: false
allow demo: false
exitpage: ${landing_url}
db:
  prefix: postgresql+psycopg2://
  name: ${db_name}
  user: ${db_user}
  password: ${db_password}
  host: ${db_host}
  port: ${db_port}
  table prefix: null
  backup: false
secretkey: ${secretkey}
backup days: 14
default title: Debt Collective Tools
default short title: Tools
mail:
  default sender: ${default_sender}
  mailgun api key: ${mailgun_api_key}
  mailgun domain: ${mailgun_domain}
  mailgun api url: ${mailgun_api_url}
server administrator email: ${server_admin_email}
default interview: ${default_interview}
language: en
locale: en_US.utf8
os locale: en_US.UTF-8 UTF-8
timezone: America/Los_Angeles
rabbitmq: ${rabbitmq}
redis: ${redis_url}
voicerss:
  enable: True
  key: ${voicerss_key}
  dialects:
    en: us
    es: mx
s3:
  enable: true
  access key id: ${s3_access_key_id}
  secret access key: ${s3_secret_access_key}
  bucket: ${s3_bucket}
  region: ${s3_region}
  endpoint url: null
python packages: 
  %{~ for package in pythonpackages  ~}
  - ${package}
  %{~ endfor ~}
collect statistics: false
google:
  analytics id: G-6XWC1N8GFM
ec2: true
log server: 172.17.0.2
use cloud urls: false
use minio: false
use https: false
use lets encrypt: false
lets encrypt email: null
behind https load balancer: true
xsendfile: false
update on start: true
allow updates: true
url root: https://${domain}
external hostname: ${domain}
expose websockets: false
websockets ip: null
websockets port: null
root: /
words:
  - docassemble.base:data/sources/us-words.yml
  - docassemble.bailbonds:data/sources/es-words.yml
  - docassemble.evictiondefense:data/sources/es-words.yml
  - docassemble.evictiondefense:data/sources/hy-words.yml
  - docassemble.evictiondefense:data/sources/ko-words.yml
  - docassemble.evictiondefense:data/sources/tl-words.yml
  - docassemble.evictiondefense:data/sources/zh-words.yml
  - docassemble.evictiondefense:data/sources/zht-words.yml
allow non-idempotent questions: false
restrict input variables: True
web server: nginx
new markdown to docx: True
stable version: false
sql ping: false
default icons: font awesome
favicon: docassemble.evictiondefense:data/static/favicon
student lawyer email: ${mail_lawyer_student}
bail lawyer email: ${mail_lawyer_bail}
lawyer email: ${mail_lawyer}
cc email: ${mail_cc}
zapier tpt email: ${mail_email_zapier}
zapier bail email: ${server_admin_email}
resume interview after login: True
interview delete days: 0
dispatch:
  eviction: docassemble.evictiondefense:data/questions/interview.yml
  bail: docassemble.bailbonds:data/questions/interview.yml
  student: docassemble.studentdebt:data/questions/interview.yml
  discovery: docassemble.discovery:data/questions/interview.yml
global css: /packagestatic/docassemble.bailbonds/dist/css/globalStyles.css
global javascript: /packagestatic/docassemble.bailbonds/dist/js/global.js
maximum content length: 0
