---
ga_universal_tracking_code: '${ga_universal_tracking_code}'
sso_secret: '${sso_secret}'
sso_provider_secrets: '*|${sso_secret}'
reply_by_email_address: '${reply_by_email_address}'
pop3_polling_host: '${pop3_polling_host}'
pop3_polling_port: '${pop3_polling_port}'
pop3_polling_username: '${pop3_polling_username}'
pop3_polling_password: '${pop3_polling_password}'
enable_s3_uploads: 'true'
s3_access_key_id: '${s3_access_key_id}'
s3_secret_access_key: '${s3_secret_access_key}'
s3_upload_bucket: '${s3_upload_bucket}'
s3_cdn_url: '${s3_cdn_url}'
force_https: 'true'
backup_location: s3
backup_frequency: '${backup_frequency}'
s3_backup_bucket: '${s3_backup_bucket}'
