---
title: The Debt Collective
site_description: A place to organize to fight debt
contact_email: admin@debtcollective.org
contact_url: admin@debtcollective.org
notification_email: noreply@debtcollective.org
site_contact_username: system
logo_url: "//s3.amazonaws.com/tds-static/img/debtcollective/0.0.1/DC-logo_FULL_WHITE%403x.png"
logo_small_url: "//s3.amazonaws.com/tds-static/img/debtcollective/0.0.1/DC-logo-small%403x.png"
large_icon: "/uploads/default/original/1X/0d0a33040cacda0e9ac4c224c33e2bcb25d60329.png"
favicon_url: "//s3.amazonaws.com/tds-static/img/debtcollective/0.0.1/favicon.png"
apple_touch_icon_url: "//s3.amazonaws.com/tds-static/img/debtcollective/0.0.1/DC-logo-small%403x.png"
ga_universal_tracking_code: "${ga_universal_tracking_code}"
category_colors: BF1E2E|F1592A|F7941D|9EB83B|3AB54A|12A89D|25AAE2|0E76BD|652D90|92278F|ED207B|8C6238|231F20|808281|B3B5B4|283890
push_notifications_prompt: "false"
enable_local_logins_via_email: "false"
sso_allows_all_return_paths: "true"
enable_sso_provider: "true"
verbose_sso_logging: "true"
sso_secret: "${sso_secret}"
sso_provider_secrets: "*|${sso_secret}"
purge_unactivated_users_grace_period_days: "60"
public_user_custom_fields: geo_location
enable_user_directory: "false"
allow_uncategorized_topics: "false"
enable_rich_text_paste: "false"
newuser_max_attachments: "5"
digest_posts: "3"
disable_digest_emails: "true"
reply_by_email_enabled: "true"
reply_by_email_address: "${reply_by_email_address}"
pop3_polling_enabled: "true"
pop3_polling_period_mins: "2"
pop3_polling_host: "${pop3_polling_host}"
pop3_polling_port: "${pop3_polling_port}"
pop3_polling_username: "${pop3_polling_username}"
pop3_polling_password: "${pop3_polling_password}"
log_mail_processing_failures: "true"
delete_email_logs_after_days: "365"
max_image_size_kb: "3072"
max_attachment_size_kb: "3072"
authorized_extensions: jpg|jpeg|png|gif|pdf|tiff
purge_deleted_uploads_grace_period_days: "90"
enable_s3_uploads: "true"
s3_access_key_id: "${s3_access_key_id}"
s3_secret_access_key: "${s3_secret_access_key}"
s3_upload_bucket: "${s3_upload_bucket}"
s3_cdn_url: "${s3_cdn_url}"
allow_all_attachments_for_group_messages: "true"
default_trust_level: "1"
min_trust_to_edit_wiki_post: "3"
send_tl1_welcome_message: "false"
force_https: "true"
cors_origins: https://tools.debtcollective.org|https://wiki.debtcollective.org|https://media.debtcollective.org|https://debtcollective.org|http://powerreport.debtcollective.org
blacklisted_crawler_user_agents: ""
max_topics_per_day: "500"
max_topics_in_first_day: "500"
max_replies_in_first_day: "25"
tl2_additional_likes_per_day_multiplier: "500.0"
max_post_deletions_per_minute: "10"
max_post_deletions_per_day: "50"
backup_location: s3
backup_frequency: "${backup_frequency}"
s3_backup_bucket: "${s3_backup_bucket}"
tagging_enabled: "true"
disable_discourse_narrative_bot_welcome_post: "true"
discourse_narrative_bot_welcome_post_delay: "10"
debtcollective_header_links:
  Dispute Your Debt, Dispute Your Debt, https://tools.debtcollective.org, vdo, self, remove|
  The Power Report, The Power Report, https://powerreport.debtcollective.org, vdo, self, remove|
  Donate, Donate, https://tools.debtcollective.org/donate, vdo, self, remove
debtcollective_solidarity_message_author: Laura_Hanna
private_message_menu: like-count|like|flag|edit|bookmark|delete|admin|reply
assign_enabled: "true"
location_input_fields_enabled: "false"
events_enabled: "true"
events_agenda_enabled: "true"
events_calendar_enabled: "true"
events_add_to_calendar: "true"
